apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-earthquake-app
  labels:
    app: flask-earthquake-app
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: flask-earthquake-app
  template:
    metadata:
      labels:
        app: flask-earthquake-app
    spec:
      containers:
      - name: flask-earthquake-app
        image: 549955071813.dkr.ecr.eu-central-1.amazonaws.com/flask_earthquake_v1:latest
        ports:
        - containerPort: 5001
