apiVersion: v1
kind: Service
metadata:
  name: flask-earthquake-service
spec:
  selector:
    app: flask-earthquake-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer  # Exposes the service externally using a load balancer

